var singleDemoInfo = {
	Game: "Doom2",
	Activity: [
		{ Tic: 1, Operation: "Map", MapName: "MAP07" },
		{ Tic: 2, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 311, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 341, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "unicode" },
		{ Tic: 469, Operation: "Say", PlayerName: "darway", Message: "HI" },
		{ Tic: 584, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 587, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "unicode" },
		{ Tic: 614, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "mario" },
		{ Tic: 666, Operation: "Kick", PlayerName: "mario", MessageType: 3 },
		{ Tic: 690, Operation: "Say", PlayerName: "darway", Message: "HI" },
		{ Tic: 782, Operation: "Say", PlayerName: "unicode", Message: "GOGO" },
		{ Tic: 872, Operation: "Say", PlayerName: "darway", Message: "??" },
		{ Tic: 917, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 920, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "unicode" },
		{ Tic: 949, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "mario" },
		{ Tic: 1102, Operation: "Say", PlayerName: "mario", Message: "OK" },
		{ Tic: 1381, Operation: "Map", MapName: "map07" },
		{ Tic: 1532, Operation: "Say", PlayerName: "darway", Message: "GO" },
		{ Tic: 18077, Operation: "Say", PlayerName: "mario", Message: "LLAG....." },
		{ Tic: 29518, Operation: "Kick", PlayerName: "mario", MessageType: 3 },
	],
	ActivityTimeOffset: 38.0,
	ActivityTimeScale: 0.9999,
	Videos: [
		{
			PlayerName: "unicode",
			VideoID: "qJdVWMZWzas",
			ZeroTime: 1.5,
		},
		{
			PlayerName: "mario",
			VideoID: "KvRkKUNeSIg",
			ZeroTime: 1.15,
		},
	],
};
