var singleDemoInfo = {
	Game: "Doom2",
	Activity: [
		{ Tic: 1, Operation: "Map", MapName: "MAP01" },
		{ Tic: 2, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 953, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 984, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "unicode" },
		{ Tic: 1387, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 1391, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "unicode" },
		{ Tic: 1419, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "mario" },
		{ Tic: 1655, Operation: "Map", MapName: "MAP01" },
		{ Tic: 1705, Operation: "Say", PlayerName: "darway", Message: "GO" },
		{ Tic: 2437, Operation: "Say", PlayerName: "darway", Message: "MARIO VS UNICODE" },
		{ Tic: 2882, Operation: "Say", PlayerName: "darway", Message: "2 GUY ADD OIL" },
		{ Tic: 10662, Operation: "Say", PlayerName: "mario", Message: "..." },
		{ Tic: 17771, Operation: "Say", PlayerName: "mario", Message: "OK" },
		{ Tic: 17894, Operation: "Say", PlayerName: "mario", Message: "YOU WIN" },
		{ Tic: 17982, Operation: "Say", PlayerName: "unicode", Message: "..." },
		{ Tic: 18284, Operation: "Say", PlayerName: "mario", Message: "....." },
		{ Tic: 18293, Operation: "Say", PlayerName: "unicode", Message: "NEVER GIVE UP" },
		{ Tic: 18587, Operation: "Say", PlayerName: "mario", Message: "46.." },
		{ Tic: 18807, Operation: "Say", PlayerName: "mario", Message: "45.." },
		{ Tic: 30708, Operation: "Say", PlayerName: "mario", Message: "T...." },
		{ Tic: 34016, Operation: "Say", PlayerName: "mario", Message: "......" },
		{ Tic: 34143, Operation: "Say", PlayerName: "unicode", Message: "???" },
		{ Tic: 35316, Operation: "Say", PlayerName: "mario", Message: "..." },
		{ Tic: 37378, Operation: "Kick", PlayerName: "mario", MessageType: 3 },
	],
	ActivityTimeOffset: 45.0,
	ActivityTimeScale: 0.9998,
	Videos: [
		{
			PlayerName: "unicode",
			VideoID: "ah1bW6oEUWc",
			ZeroTime: 1.3,
		},
		{
			PlayerName: "mario",
			VideoID: "3dluwqKsq0Q",
			ZeroTime: 1.15,
		},
	],
};
