var singleDemoInfo = {
	Game: "Doom2",
	Activity: [
		{ Tic: 1, Operation: "Map", MapName: "MAP01" },
		{ Tic: 2, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 492, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 525, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "aj" },
		{ Tic: 562, Operation: "Kick", PlayerName: "aj", MessageType: 3 },
		{ Tic: 772, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 803, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "aj" },
		{ Tic: 1091, Operation: "Say", PlayerName: "darway", Message: "HI" },
		{ Tic: 1167, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 1171, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "aj" },
		{ Tic: 1197, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "rei" },
		{ Tic: 1225, Operation: "Say", PlayerName: "aj", Message: "TODAY NO WEAR GLASSES" },
		{ Tic: 1321, Operation: "Say", PlayerName: "aj", Message: "HARD TO SEE XD" },
		{ Tic: 1479, Operation: "Say", PlayerName: "darway", Message: "WAIT" },
		{ Tic: 1642, Operation: "Say", PlayerName: "aj", Message: "RESET" },
		{ Tic: 1707, Operation: "Map", MapName: "MAP01" },
		{ Tic: 1751, Operation: "Say", PlayerName: "darway", Message: "GO" },
		{ Tic: 23082, Operation: "Say", PlayerName: "aj", Message: "( Y )" },
		{ Tic: 41907, Operation: "Say", PlayerName: "rei", Message: "WAIT" },
		{ Tic: 41986, Operation: "Say", PlayerName: "aj", Message: "?" },
		{ Tic: 42055, Operation: "Say", PlayerName: "rei", Message: "PAUSE" },
		{ Tic: 42253, Operation: "Say", PlayerName: "aj", Message: "??" },
		{ Tic: 42391, Operation: "Say", PlayerName: "rei", Message: "GARBEGE" },
		{ Tic: 42515, Operation: "Say", PlayerName: "aj", Message: "- -" },
		{ Tic: 42644, Operation: "Say", PlayerName: "rei", Message: "SORRY" },
		{ Tic: 42771, Operation: "Say", PlayerName: "rei", Message: "WAIT.." },
		{ Tic: 42877, Operation: "Say", PlayerName: "aj", Message: "XD.." },
		{ Tic: 46558, Operation: "Say", PlayerName: "aj", Message: "ZZZ..." },
		{ Tic: 46680, Operation: "Say", PlayerName: "aj", Message: "-3-" },
		{ Tic: 46729, Operation: "Say", PlayerName: "aj", Message: "=3=" },
		{ Tic: 46785, Operation: "Say", PlayerName: "aj", Message: "\\3\\" },
		{ Tic: 46841, Operation: "Say", PlayerName: "aj", Message: "/3\\" },
		{ Tic: 46963, Operation: "Say", PlayerName: "rei", Message: "SORRY" },
		{ Tic: 47057, Operation: "Say", PlayerName: "aj", Message: "OK?" },
		{ Tic: 47066, Operation: "Say", PlayerName: "rei", Message: "BACK" },
		{ Tic: 56160, Operation: "Say", PlayerName: "rei", Message: "OK" },
		{ Tic: 56210, Operation: "Say", PlayerName: "aj", Message: "XD" },
		{ Tic: 56326, Operation: "Say", PlayerName: "aj", Message: "FRAG 45?" },
		{ Tic: 56386, Operation: "Say", PlayerName: "rei", Message: "LOST" },
	],
	ActivityTimeOffset: 48.5,
	Videos: [
		{
			PlayerName: "aj",
			VideoID: "vkrpHBzgPmU",
			ZeroTime: 0.97,
		},
		{
			PlayerName: "rei",
			VideoID: "8up1rqkltaY",
			ZeroTime: 0.87,
		},
	],
};
