var singleDemoInfo = {
	Game: "Doom2",
	Activity: [
		{ Tic: 1, Operation: "Map", MapName: "MAP07" },
		{ Tic: 2, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 469, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 505, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "link" },
		{ Tic: 581, Operation: "Say", PlayerName: "link", Message: "WAIT" },
		{ Tic: 630, Operation: "Say", PlayerName: "darway", Message: "WAIT" },
		{ Tic: 677, Operation: "Say", PlayerName: "link", Message: "WAIT" },
		{ Tic: 1842, Operation: "Say", PlayerName: "darway", Message: "WAIT UNICODE" },
		{ Tic: 2017, Operation: "Say", PlayerName: "link", Message: "OO" },
		{ Tic: 2076, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 2080, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "link" },
		{ Tic: 2101, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "unicode" },
		{ Tic: 2239, Operation: "Say", PlayerName: "darway", Message: "WAIT" },
		{ Tic: 2424, Operation: "Map", MapName: "map07" },
		{ Tic: 2483, Operation: "Say", PlayerName: "darway", Message: "GO" },
		{ Tic: 2635, Operation: "Say", PlayerName: "unicode", Message: "I WANT TO EAT" },
		{ Tic: 2822, Operation: "Say", PlayerName: "darway", Message: "??" },
		{ Tic: 4842, Operation: "Say", PlayerName: "link", Message: "LAG" },
		{ Tic: 4987, Operation: "Say", PlayerName: "link", Message: "OK" },
		{ Tic: 6307, Operation: "Say", PlayerName: "unicode", Message: "?" },
		{ Tic: 6584, Operation: "Say", PlayerName: "link", Message: "NO" },
		{ Tic: 6697, Operation: "Say", PlayerName: "link", Message: "WAUT" },
		{ Tic: 6834, Operation: "Say", PlayerName: "link", Message: "OK" },
		{ Tic: 6854, Operation: "Say", PlayerName: "unicode", Message: "??" },
		{ Tic: 16310, Operation: "Say", PlayerName: "link", Message: ",MMM" },
		{ Tic: 22346, Operation: "Say", PlayerName: "link", Message: "..." },
		{ Tic: 36523, Operation: "Say", PlayerName: "link", Message: "NO" },
		{ Tic: 41744, Operation: "Say", PlayerName: "link", Message: "COOL" },
		{ Tic: 41875, Operation: "Say", PlayerName: "unicode", Message: ".." },
		{ Tic: 43931, Operation: "Say", PlayerName: "link", Message: "HO" },
		{ Tic: 45621, Operation: "Say", PlayerName: "link", Message: "GOOD" },
		{ Tic: 46841, Operation: "Kick", PlayerName: "link", MessageType: 3 },
	],
	ActivityTimeOffset: 68.5,
	ActivityTimeScale: 0.9998,
	Videos: [
		{
			PlayerName: "link",
			VideoID: "YuNg0pEuO9w",
			ZeroTime: 0.95,
		},
		{
			PlayerName: "unicode",
			VideoID: "hCa3AAE073s",
			ZeroTime: 1.05,
		},
	],
};
