var singleDemoInfo = {
	Game: "Doom2",
	Activity: [
		{ Tic: 1, Operation: "Map", MapName: "MAP07" },
		{ Tic: 2, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 160, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 192, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "hunter" },
		{ Tic: 652, Operation: "Say", PlayerName: "darway", Message: "WAIT" },
		{ Tic: 2221, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 2225, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "hunter" },
		{ Tic: 2250, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "unicode" },
		{ Tic: 2331, Operation: "Say", PlayerName: "darway", Message: "WAIT" },
		{ Tic: 2591, Operation: "Map", MapName: "map07" },
		{ Tic: 2640, Operation: "Say", PlayerName: "unicode", Message: "EA WAIT" },
		{ Tic: 2668, Operation: "Say", PlayerName: "darway", Message: "GO" },
		{ Tic: 2735, Operation: "Say", PlayerName: "unicode", Message: "WAIT" },
		{ Tic: 2851, Operation: "Say", PlayerName: "hunter", Message: "MM" },
		{ Tic: 2863, Operation: "Say", PlayerName: "darway", Message: "WAIT" },
		{ Tic: 3564, Operation: "Say", PlayerName: "unicode", Message: "NO MUSIC XD" },
		{ Tic: 3714, Operation: "Say", PlayerName: "hunter", Message: "XD" },
		{ Tic: 3774, Operation: "Say", PlayerName: "darway", Message: "OH....." },
		{ Tic: 3938, Operation: "Say", PlayerName: "darway", Message: "EXIT ?" },
		{ Tic: 3945, Operation: "Say", PlayerName: "hunter", Message: "HI ALL" },
		{ Tic: 4265, Operation: "Say", PlayerName: "unicode", Message: "FORGOT IT" },
		{ Tic: 4330, Operation: "Say", PlayerName: "unicode", Message: "GO" },
		{ Tic: 4361, Operation: "Say", PlayerName: "darway", Message: "GO" },
		{ Tic: 28123, Operation: "Say", PlayerName: "unicode", Message: "..." },
		{ Tic: 28362, Operation: "Say", PlayerName: "unicode", Message: "?" },
		{ Tic: 28366, Operation: "Say", PlayerName: "hunter", Message: "WAIT" },
		{ Tic: 28479, Operation: "Say", PlayerName: "hunter", Message: "PHONE" },
		{ Tic: 28582, Operation: "Say", PlayerName: "unicode", Message: "..." },
		{ Tic: 28672, Operation: "Say", PlayerName: "hunter", Message: "OK" },
		{ Tic: 38709, Operation: "Say", PlayerName: "unicode", Message: "./.." },
		{ Tic: 38832, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 38835, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "unicode" },
		{ Tic: 38837, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "hunter" },
		{ Tic: 38862, Operation: "SetPlayer", PlayerNumber: 3, PlayerName: "artist-hong" },
		{ Tic: 38951, Operation: "Say", PlayerName: "hunter", Message: "=.=" },
		{ Tic: 39136, Operation: "Say", PlayerName: "darway", Message: "GET OUY" },
		{ Tic: 39354, Operation: "Say", PlayerName: "unicode", Message: "..." },
		{ Tic: 39424, Operation: "Kick", PlayerName: "artist-hong", MessageType: 3 },
		{ Tic: 39425, Operation: "Say", PlayerName: "hunter", Message: "WA LA" },
	],
	ActivityTimeOffset: 73,
	ActivityTimeScale: 0.9998,
	Videos: [
		{
			PlayerName: "hunter",
			VideoID: "G0GRIKnVdL8",
			ZeroTime: 1.2,
		},
		{
			PlayerName: "unicode",
			VideoID: "znGfAB3lQh4",
			ZeroTime: 1.0,
		},
	],
};
