var singleDemoInfo = {
	Game: "Doom2",
	Activity: [
		{ Tic: 1, Operation: "Map", MapName: "MAP01" },
		{ Tic: 2, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 454, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 485, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 493, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "rock1246" },
		{ Tic: 515, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "rock1246" },
		{ Tic: 515, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "james bond" },
		{ Tic: 574, Operation: "Say", PlayerName: "rock1246", Message: "Z" },
		{ Tic: 631, Operation: "Say", PlayerName: "darway", Message: "GO" },
		{ Tic: 659, Operation: "Say", PlayerName: "rock1246", Message: "RE?" },
		{ Tic: 2079, Operation: "Say", PlayerName: "james bond", Message: "WW??" },
		{ Tic: 3737, Operation: "Say", PlayerName: "rock1246", Message: "SO ( Y )" },
		{ Tic: 8413, Operation: "Say", PlayerName: "rock1246", Message: "HMM" },
		{ Tic: 52441, Operation: "Say", PlayerName: "james bond", Message: "OK" },
		{ Tic: 52531, Operation: "Say", PlayerName: "james bond", Message: "YOU GOOD" },
		{ Tic: 52849, Operation: "Say", PlayerName: "rock1246", Message: "O.." },
		{ Tic: 52961, Operation: "Say", PlayerName: "rock1246", Message: "DAR?" },
		{ Tic: 53113, Operation: "Say", PlayerName: "james bond", Message: "KILL MWE" },
		{ Tic: 53332, Operation: "Say", PlayerName: "james bond", Message: "SA" },
		{ Tic: 53451, Operation: "Say", PlayerName: "james bond", Message: "??" },
		{ Tic: 53935, Operation: "Say", PlayerName: "james bond", Message: "??" },
		{ Tic: 54092, Operation: "Say", PlayerName: "rock1246", Message: "- -\"" },
		{ Tic: 54287, Operation: "Say", PlayerName: "james bond", Message: "??>" },
		{ Tic: 54313, Operation: "Say", PlayerName: "rock1246", Message: "HMM" },
		{ Tic: 54361, Operation: "Say", PlayerName: "darway", Message: "JAMES ?" },
		{ Tic: 54453, Operation: "Say", PlayerName: "james bond", Message: "KILL ME" },
		{ Tic: 54597, Operation: "Say", PlayerName: "james bond", Message: "GO" },
		{ Tic: 54697, Operation: "Say", PlayerName: "darway", Message: "YOU LOST ?" },
		{ Tic: 54848, Operation: "Say", PlayerName: "james bond", Message: "NO" },
		{ Tic: 54883, Operation: "Say", PlayerName: "james bond", Message: "GO" },
		{ Tic: 55058, Operation: "Say", PlayerName: "darway", Message: "GO" },
		{ Tic: 55195, Operation: "Say", PlayerName: "james bond", Message: "LOST" },
		{ Tic: 55404, Operation: "Say", PlayerName: "rock1246", Message: "._." },
		{ Tic: 55791, Operation: "Kick", PlayerName: "james bond", MessageType: 3 },
		{ Tic: 55801, Operation: "Kick", PlayerName: "rock1246", MessageType: 3 },
	],
	ActivityTimeOffset: 13,
	ActivityTimeScale: 0.9998,
	Videos: [
		{
			PlayerName: "rock1246",
			VideoID: "Yj36MnS-_UY",
			ZeroTime: 0.8,
		},
		{
			PlayerName: "james bond",
			VideoID: "bby14OJIMXo",
			ZeroTime: 0.9,
		},
	],
};
