var singleDemoInfo = {
	Game: "Doom2",
	Activity: [
		{ Tic: 1, Operation: "Map", MapName: "MAP07" },
		{ Tic: 2, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 343, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 374, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "mario" },
		{ Tic: 433, Operation: "Say", PlayerName: "darway", Message: "HI" },
		{ Tic: 513, Operation: "Say", PlayerName: "mario", Message: "HI" },
		{ Tic: 568, Operation: "Say", PlayerName: "darway", Message: "WAIT" },
		{ Tic: 1021, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 1024, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "mario" },
		{ Tic: 1054, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "rock1246" },
		{ Tic: 1106, Operation: "Say", PlayerName: "darway", Message: "HI" },
		{ Tic: 1215, Operation: "Say", PlayerName: "rock1246", Message: "HI" },
		{ Tic: 1230, Operation: "Say", PlayerName: "darway", Message: "WAIT" },
		{ Tic: 1337, Operation: "Say", PlayerName: "mario", Message: "OK" },
		{ Tic: 1339, Operation: "Map", MapName: "map07" },
		{ Tic: 1386, Operation: "Say", PlayerName: "darway", Message: "GO" },
		{ Tic: 1391, Operation: "Say", PlayerName: "mario", Message: "HGO" },
		{ Tic: 2960, Operation: "Say", PlayerName: "mario", Message: "XD" },
		{ Tic: 3066, Operation: "Say", PlayerName: "rock1246", Message: "M" },
		{ Tic: 3190, Operation: "Say", PlayerName: "mario", Message: "HA" },
		{ Tic: 28665, Operation: "Say", PlayerName: "mario", Message: "LAFQ" },
		{ Tic: 29110, Operation: "Kick", PlayerName: "mario", MessageType: 3 },
		{ Tic: 29114, Operation: "Kick", PlayerName: "rock1246", MessageType: 3 },
	],
	ActivityTimeOffset: 37,
	ActivityTimeScale: 0.9998,
	Videos: [
		{
			PlayerName: "mario",
			VideoID: "DrL5TO3jj1k",
			ZeroTime: 1.0,
		},
		{
			PlayerName: "rock1246",
			VideoID: "ooLfA7M8rxA",
			ZeroTime: 1.0,
		},
	],
};
