var singleDemoInfo = {
	Game: "Doom2",
	Activity: [
		{ Tic: 1, Operation: "Map", MapName: "MAP07" },
		{ Tic: 2, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "mario" },
		{ Tic: 4, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "mario" },
		{ Tic: 34, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "dino" },
		{ Tic: 342, Operation: "Say", PlayerName: "mario", Message: "OH" },
		{ Tic: 533, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "mario" },
		{ Tic: 537, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "dino" },
		{ Tic: 565, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "hunter" },
		{ Tic: 626, Operation: "Say", PlayerName: "mario", Message: "GO?" },
		{ Tic: 875, Operation: "Say", PlayerName: "mario", Message: "GO!!" },
		{ Tic: 1370, Operation: "Say", PlayerName: "hunter", Message: "RE" },
		{ Tic: 1454, Operation: "Say", PlayerName: "hunter", Message: "RE MAP" },
		{ Tic: 1539, Operation: "Say", PlayerName: "dino", Message: "MM" },
		{ Tic: 1723, Operation: "Say", PlayerName: "mario", Message: "I NO ) (" },
		{ Tic: 1828, Operation: "Say", PlayerName: "dino", Message: "XD" },
		{ Tic: 1893, Operation: "Say", PlayerName: "hunter", Message: "@.@" },
		{ Tic: 1962, Operation: "Say", PlayerName: "dino", Message: "H KME" },
		{ Tic: 2027, Operation: "Say", PlayerName: "mario", Message: "QQ" },
		{ Tic: 2219, Operation: "Say", PlayerName: "dino", Message: "HU K ME" },
		{ Tic: 2682, Operation: "Say", PlayerName: "dino", Message: "XD" },
		{ Tic: 3018, Operation: "Say", PlayerName: "dino", Message: "K ME" },
		{ Tic: 3299, Operation: "Say", PlayerName: "hunter", Message: "??" },
		{ Tic: 3326, Operation: "Say", PlayerName: "dino", Message: "OK GO" },
		{ Tic: 3696, Operation: "Say", PlayerName: "mario", Message: "OK 46 OK?" },
		{ Tic: 3910, Operation: "Say", PlayerName: "hunter", Message: "OK" },
		{ Tic: 14904, Operation: "Say", PlayerName: "mario", Message: "Y..." },
	],
	ActivityTimeOffset: 0.15,
	Videos: [
		{
			PlayerName: "dino",
			VideoID: "ju6DRvWMqPs",
			ZeroTime: 1.3,
		},
		{
			PlayerName: "hunter",
			VideoID: "GDt5Oaszszg",
			ZeroTime: 1.234,
		},
	],
};
