var singleDemoInfo = {
	Game: "",
	Activity: [
		{ Tic: 1, Operation: "Map", MapName: "MAP07" },
		{ Tic: 2, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 644, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 675, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "dino" },
		{ Tic: 1170, Operation: "Say", PlayerName: "darway", Message: "WAIT" },
		{ Tic: 1302, Operation: "Say", PlayerName: "dino", Message: "MM]" },
		{ Tic: 1581, Operation: "Say", PlayerName: "darway", Message: "I WILL RE-START" },
		{ Tic: 1766, Operation: "Say", PlayerName: "dino", Message: "MM" },
		{ Tic: 2109, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 2112, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "dino" },
		{ Tic: 2139, Operation: "Say", PlayerName: "darway", Message: "HI" },
		{ Tic: 2139, Operation: "Kick", PlayerName: "", MessageType: 4 },
		{ Tic: 2139, Operation: "Say", PlayerName: "dino", Message: "GO" },
		{ Tic: 2308, Operation: "Say", PlayerName: "dino", Message: "...." },
		{ Tic: 2366, Operation: "Say", PlayerName: "darway", Message: "??" },
		{ Tic: 3568, Operation: "Say", PlayerName: "darway", Message: "LINK VS DINO" },
		{ Tic: 3997, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 4000, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "dino" },
		{ Tic: 4040, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "link" },
		{ Tic: 4071, Operation: "Say", PlayerName: "darway", Message: "HI" },
		{ Tic: 4180, Operation: "Say", PlayerName: "link", Message: "WAIT" },
		{ Tic: 4283, Operation: "Say", PlayerName: "link", Message: "I VIDIO" },
		{ Tic: 4315, Operation: "Say", PlayerName: "dino", Message: "OK" },
		{ Tic: 4360, Operation: "Say", PlayerName: "darway", Message: "RE-START" },
		{ Tic: 4542, Operation: "Say", PlayerName: "link", Message: "OK" },
		{ Tic: 4610, Operation: "Say", PlayerName: "dino", Message: "OK" },
		{ Tic: 4698, Operation: "Map", MapName: "map07" },
		{ Tic: 4778, Operation: "Say", PlayerName: "darway", Message: "GO" },
		{ Tic: 5319, Operation: "Say", PlayerName: "darway", Message: "GAME IS START!!!!" },
		{ Tic: 26295, Operation: "Say", PlayerName: "link", Message: "LAG" },
		{ Tic: 26463, Operation: "Say", PlayerName: "dino", Message: "OH" },
	],
	ActivityTimeOffset: 132.5,
	ActivityTimeScale: 0.9998,
	Videos: [
		{
			PlayerName: "dino",
			VideoID: "sK8vThrUw-w",
			ZeroTime: 1.05,
		},
		{
			PlayerName: "link",
			VideoID: "ncZRxvLXinM",
			ZeroTime: 1.25,
		},
	],
};
