var singleDemoInfo = {
	Game: "Doom2",
	Activity: [
		{ Tic: 1, Operation: "Map", MapName: "MAP01" },
		{ Tic: 2, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 438, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 469, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "Howie" },
		{ Tic: 1278, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 1280, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "Howie" },
		{ Tic: 1287, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 1289, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "Howie" },
		{ Tic: 1308, Operation: "SetPlayer", PlayerNumber: 3, PlayerName: "doomenergy" },
		{ Tic: 1310, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 1310, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 1357, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "darway" },
		{ Tic: 1359, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "Howie" },
		{ Tic: 1360, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 1360, Operation: "SetPlayer", PlayerNumber: 3, PlayerName: "doomenergy" },
		{ Tic: 1387, Operation: "Say", PlayerName: "doomenergy", Message: "HI" },
		{ Tic: 1401, Operation: "SetPlayer", PlayerNumber: 4, PlayerName: "qqw94" },
		{ Tic: 1549, Operation: "Say", PlayerName: "doomenergy", Message: "HI" },
		{ Tic: 1576, Operation: "Say", PlayerName: "qqw94", Message: ".........." },
		{ Tic: 1631, Operation: "Say", PlayerName: "qqw94", Message: "HI" },
		{ Tic: 1735, Operation: "Say", PlayerName: "Howie", Message: "HELLO" },
		{ Tic: 1769, Operation: "Say", PlayerName: "darway", Message: "NOW UV+FSAT" },
		{ Tic: 1806, Operation: "Say", PlayerName: "ringo", Message: "= =" },
		{ Tic: 1846, Operation: "Say", PlayerName: "doomenergy", Message: "....." },
		{ Tic: 2446, Operation: "Say", PlayerName: "Howie", Message: "RESPAWN?" },
		{ Tic: 2786, Operation: "Say", PlayerName: "ringo", Message: "LET ME CHANGE MY COLOUR- -" },
		{ Tic: 3150, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 3163, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 3168, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 3184, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 3201, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 3207, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 3225, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 3248, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 3285, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 3302, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 3317, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 3331, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 3356, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "ringo" },
		{ Tic: 4505, Operation: "Say", PlayerName: "ringo", Message: "ITEM RESPAWN- -?" },
		{ Tic: 4840, Operation: "Say", PlayerName: "darway", Message: "YES" },
		{ Tic: 10697, Operation: "Say", PlayerName: "ringo", Message: "- --" },
		{ Tic: 10784, Operation: "Say", PlayerName: "qqw94", Message: ".....XD" },
		{ Tic: 14962, Operation: "Say", PlayerName: "ringo", Message: "SRY= =" },
		{ Tic: 15136, Operation: "Say", PlayerName: "darway", Message: "IS OK" },
		{ Tic: 16327, Operation: "Say", PlayerName: "ringo", Message: "=3=" },
		{ Tic: 16358, Operation: "Say", PlayerName: "qqw94", Message: "SRY" },
		{ Tic: 16547, Operation: "Say", PlayerName: "ringo", Message: "NVM" },
		{ Tic: 18294, Operation: "Say", PlayerName: "qqw94", Message: "....??" },
		{ Tic: 18409, Operation: "Say", PlayerName: "qqw94", Message: "XD" },
		{ Tic: 18748, Operation: "Say", PlayerName: "qqw94", Message: "GO" },
		{ Tic: 19674, Operation: "Say", PlayerName: "doomenergy", Message: "SORRY" },
		{ Tic: 19798, Operation: "Say", PlayerName: "ringo", Message: "SORRY" },
		{ Tic: 19959, Operation: "Say", PlayerName: "qqw94", Message: "><XDDDDD" },
		{ Tic: 21474, Operation: "Say", PlayerName: "ringo", Message: "XD" },
		{ Tic: 21475, Operation: "Say", PlayerName: "qqw94", Message: "XD" },
		{ Tic: 21834, Operation: "Say", PlayerName: "qqw94", Message: "XD" },
		{ Tic: 21949, Operation: "Say", PlayerName: "qqw94", Message: "XD" },
		{ Tic: 22307, Operation: "Say", PlayerName: "qqw94", Message: "......" },
		{ Tic: 22389, Operation: "Say", PlayerName: "darway", Message: "I AM OK" },
		{ Tic: 22461, Operation: "Say", PlayerName: "ringo", Message: "=3=" },
		{ Tic: 22484, Operation: "Say", PlayerName: "qqw94", Message: "OK" },
		{ Tic: 22599, Operation: "Say", PlayerName: "doomenergy", Message: "Y" },
		{ Tic: 22778, Operation: "Say", PlayerName: "qqw94", Message: "XDDDD" },
		{ Tic: 23161, Operation: "Say", PlayerName: "darway", Message: "FLY" },
		{ Tic: 23328, Operation: "Say", PlayerName: "ringo", Message: "YESXD" },
		{ Tic: 23404, Operation: "Say", PlayerName: "qqw94", Message: "XDDDDDD" },
		{ Tic: 23818, Operation: "Say", PlayerName: "qqw94", Message: "XDDDDD" },
		{ Tic: 23819, Operation: "Say", PlayerName: "doomenergy", Message: "XXDDDDDDD" },
		{ Tic: 24180, Operation: "Say", PlayerName: "doomenergy", Message: "XDDDDDDDD" },
		{ Tic: 24326, Operation: "Say", PlayerName: "qqw94", Message: "WAIT ME./....XD" },
		{ Tic: 24333, Operation: "Say", PlayerName: "ringo", Message: "=3=" },
		{ Tic: 24354, Operation: "Say", PlayerName: "darway", Message: "WA LAY" },
		{ Tic: 24481, Operation: "Say", PlayerName: "ringo", Message: "I WINXD" },
		{ Tic: 24570, Operation: "Say", PlayerName: "darway", Message: "XD" },
		{ Tic: 25125, Operation: "Say", PlayerName: "ringo", Message: "WOW= =" },
		{ Tic: 25300, Operation: "Say", PlayerName: "qqw94", Message: "XD" },
		{ Tic: 26659, Operation: "Say", PlayerName: "doomenergy", Message: "XDDDDDD" },
		{ Tic: 26667, Operation: "Say", PlayerName: "qqw94", Message: "XD" },
		{ Tic: 26721, Operation: "Map", MapName: "MAP02" },
		{ Tic: 26759, Operation: "Say", PlayerName: "doomenergy", Message: "XDDDDDDD" },
		{ Tic: 26786, Operation: "Say", PlayerName: "ringo", Message: "-.-" },
		{ Tic: 26788, Operation: "Kick", PlayerName: "Howie", MessageType: 2 },
	],
	ActivityTimeOffset: 0,
	ActivityTimeScale: 0.9999,
	Videos: [
		{
			PlayerName: "darway",
			VideoID: "1R0k-nZrByg",
			ZeroTime: 1.25,
		},
		{
			PlayerName: "Howie",
			VideoID: "XsY-4cy1Y-8",
			ZeroTime: 1.35,
		},
		{
			PlayerName: "doomenergy",
			VideoID: "s6-aA_Wz1Fc",
			ZeroTime: 1.5,
		},
		{
			PlayerName: "ringo",
			VideoID: "ODEJKbOlgPY",
			ZeroTime: 1.8,
		},
		{
			PlayerName: "qqw94",
			VideoID: "rkVdQw-TfTQ",
			ZeroTime: 1.45,
		},
	],
};
