var singleDemoInfo = {
	Game: "Doom2",
	Activity: [
		{ Tic: 1, Operation: "Map", MapName: "MAP01" },
		{ Tic: 2, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "-=d.b=- e.f." },
		{ Tic: 627, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "-=d.b=- e.f." },
		{ Tic: 643, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "Timothy" },
		{ Tic: 814, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "HEY" },
		{ Tic: 911, Operation: "Say", PlayerName: "Timothy", Message: "XD?" },
		{ Tic: 1188, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "FRAG LIM?" },
		{ Tic: 1332, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "LIMIT" },
		{ Tic: 1453, Operation: "Say", PlayerName: "Timothy", Message: "75?100?" },
		{ Tic: 1607, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "-=d.b=- e.f." },
		{ Tic: 1613, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "Timothy" },
		{ Tic: 1632, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "QQW94" },
		{ Tic: 1633, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "75" },
		{ Tic: 1760, Operation: "Say", PlayerName: "QQW94", Message: "HI" },
		{ Tic: 1828, Operation: "Say", PlayerName: "Timothy", Message: "HI" },
		{ Tic: 2238, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "60 OK?" },
		{ Tic: 2381, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "FAGR 60" },
		{ Tic: 2444, Operation: "Say", PlayerName: "QQW94", Message: "OK" },
		{ Tic: 2714, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "GO FIRST?" },
		{ Tic: 2797, Operation: "Say", PlayerName: "Timothy", Message: "GO" },
		{ Tic: 2844, Operation: "Map", MapName: "map01" },
		{ Tic: 2845, Operation: "Say", PlayerName: "Timothy", Message: "NO" },
		{ Tic: 3000, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "OH.." },
		{ Tic: 3187, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "NO" },
		{ Tic: 3342, Operation: "Say", PlayerName: "QQW94", Message: "XD?" },
		{ Tic: 3418, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "Y" },
		{ Tic: 3442, Operation: "Say", PlayerName: "Timothy", Message: "XD" },
		{ Tic: 3918, Operation: "Say", PlayerName: "Timothy", Message: "WAIT THEM FIRST?XD" },
		{ Tic: 4278, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "I ' M OK" },
		{ Tic: 4538, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "-=d.b=- e.f." },
		{ Tic: 4542, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "QQW94" },
		{ Tic: 4543, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "Timothy" },
		{ Tic: 4553, Operation: "SetPlayer", PlayerNumber: 3, PlayerName: "Howie" },
		{ Tic: 4646, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "HI" },
		{ Tic: 4716, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "SUP" },
		{ Tic: 4727, Operation: "Say", PlayerName: "Howie", Message: "XD" },
		{ Tic: 5115, Operation: "Say", PlayerName: "Timothy", Message: "FALL WEAPON AND RJ XD" },
		{ Tic: 5116, Operation: "Say", PlayerName: "Howie", Message: "MY MOM CALLED ME TO HAVE DINNER = =" },
		{ Tic: 5180, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "LAH?" },
		{ Tic: 5359, Operation: "Say", PlayerName: "Timothy", Message: "LOL" },
		{ Tic: 5419, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "YEH.." },
		{ Tic: 5648, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "GO EAT FIRST" },
		{ Tic: 5778, Operation: "Say", PlayerName: "Howie", Message: "I ' LL BE A SPECTATOR XD" },
		{ Tic: 5914, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "C" },
		{ Tic: 5928, Operation: "Say", PlayerName: "QQW94", Message: "NO BFG...XD" },
		{ Tic: 6045, Operation: "Say", PlayerName: "Timothy", Message: "XD\"" },
		{ Tic: 6557, Operation: "Say", PlayerName: "Timothy", Message: "GO?" },
		{ Tic: 6719, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "OK" },
		{ Tic: 6998, Operation: "Map", MapName: "map01" },
		{ Tic: 7288, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "-=d.b=- e.f." },
		{ Tic: 7291, Operation: "SetPlayer", PlayerNumber: 3, PlayerName: "Howie" },
		{ Tic: 7292, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "QQW94" },
		{ Tic: 7293, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "Timothy" },
		{ Tic: 7321, Operation: "SetPlayer", PlayerNumber: 4, PlayerName: "sprite" },
		{ Tic: 7980, Operation: "Say", PlayerName: "Howie", Message: "WATCH U GUYS PLAY" },
		{ Tic: 8123, Operation: "Say", PlayerName: "Howie", Message: "HAVING DINNER" },
		{ Tic: 8535, Operation: "Say", PlayerName: "Timothy", Message: "XD?!" },
		{ Tic: 8865, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "CC" },
		{ Tic: 9822, Operation: "Say", PlayerName: "Timothy", Message: "XD '" },
		{ Tic: 10092, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "OOH" },
		{ Tic: 12862, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "LAG?" },
		{ Tic: 13046, Operation: "Say", PlayerName: "QQW94", Message: "NO" },
		{ Tic: 13104, Operation: "Say", PlayerName: "Timothy", Message: "YES" },
		{ Tic: 13243, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "OK.." },
		{ Tic: 13736, Operation: "Say", PlayerName: "Timothy", Message: "XD" },
		{ Tic: 14345, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "CC" },
		{ Tic: 14673, Operation: "Say", PlayerName: "Timothy", Message: "XD" },
		{ Tic: 16093, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "OOH" },
		{ Tic: 18089, Operation: "Say", PlayerName: "sprite", Message: "BFG??" },
		{ Tic: 18181, Operation: "Say", PlayerName: "Timothy", Message: "NO" },
		{ Tic: 18202, Operation: "Say", PlayerName: "QQW94", Message: "NOS" },
		{ Tic: 18944, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "YEH" },
		{ Tic: 21345, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "SPRITE" },
		{ Tic: 21659, Operation: "Say", PlayerName: "sprite", Message: "??" },
		{ Tic: 21899, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "LAG?" },
		{ Tic: 21948, Operation: "Say", PlayerName: "Timothy", Message: "QQ XD\"" },
		{ Tic: 22050, Operation: "Say", PlayerName: "Timothy", Message: "Y]" },
		{ Tic: 22187, Operation: "Say", PlayerName: "sprite", Message: "NO" },
		{ Tic: 26367, Operation: "Map", MapName: "map02" },
		{ Tic: 26982, Operation: "Say", PlayerName: "Timothy", Message: "BFG?" },
		{ Tic: 27208, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "NO.." },
		{ Tic: 28841, Operation: "Say", PlayerName: "QQW94", Message: "XDDDDDDDDDDDDDDD" },
		{ Tic: 28940, Operation: "Say", PlayerName: "Timothy", Message: "XD" },
		{ Tic: 29014, Operation: "Say", PlayerName: "Timothy", Message: "XDF?" },
		{ Tic: 30683, Operation: "Say", PlayerName: "Timothy", Message: "DELAY XD" },
		{ Tic: 30814, Operation: "Say", PlayerName: "Timothy", Message: "XD" },
		{ Tic: 32834, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "SERVER SHIT MASTER..XD" },
		{ Tic: 33057, Operation: "Say", PlayerName: "Timothy", Message: "XD" },
		{ Tic: 33712, Operation: "Say", PlayerName: "Timothy", Message: "SORRY" },
		{ Tic: 33802, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "NOW" },
		{ Tic: 35304, Operation: "Say", PlayerName: "sprite", Message: "SORRY" },
		{ Tic: 35479, Operation: "Say", PlayerName: "QQW94", Message: "M" },
		{ Tic: 35481, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "OKOK" },
		{ Tic: 36664, Operation: "Say", PlayerName: "QQW94", Message: "SORRY@@" },
		{ Tic: 36795, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "NO" },
		{ Tic: 37995, Operation: "Say", PlayerName: "sprite", Message: "USE BFG LA" },
		{ Tic: 38131, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "..." },
		{ Tic: 41104, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "LAG?" },
		{ Tic: 41104, Operation: "Kick", PlayerName: "sprite", MessageType: 4 },
		{ Tic: 41244, Operation: "Say", PlayerName: "QQW94", Message: "@@" },
		{ Tic: 41292, Operation: "Say", PlayerName: "Timothy", Message: "..." },
		{ Tic: 41398, Operation: "Say", PlayerName: "Timothy", Message: "DELAY" },
		{ Tic: 42407, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "CC" },
		{ Tic: 45585, Operation: "Map", MapName: "map03" },
		{ Tic: 48074, Operation: "Say", PlayerName: "Timothy", Message: ",,," },
		{ Tic: 49334, Operation: "Say", PlayerName: "QQW94", Message: "XD" },
		{ Tic: 49392, Operation: "Say", PlayerName: "Timothy", Message: "XD" },
		{ Tic: 49417, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "XD" },
		{ Tic: 49541, Operation: "Say", PlayerName: "QQW94", Message: "I CALL SPRITE" },
		{ Tic: 49639, Operation: "Kick", PlayerName: "QQW94", MessageType: 3 },
		{ Tic: 49699, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "Y" },
		{ Tic: 50285, Operation: "SetPlayer", PlayerNumber: 0, PlayerName: "-=d.b=- e.f." },
		{ Tic: 50290, Operation: "SetPlayer", PlayerNumber: 1, PlayerName: "Timothy" },
		{ Tic: 50290, Operation: "SetPlayer", PlayerNumber: 3, PlayerName: "Howie" },
		{ Tic: 50312, Operation: "SetPlayer", PlayerNumber: 2, PlayerName: "QQW94" },
		{ Tic: 50610, Operation: "Say", PlayerName: "QQW94", Message: "SHE OFF LINE@@" },
		{ Tic: 50716, Operation: "Say", PlayerName: "Timothy", Message: "XD" },
		{ Tic: 50765, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: ".." },
		{ Tic: 52565, Operation: "Say", PlayerName: "QQW94", Message: "ME SOME TIRED" },
		{ Tic: 52599, Operation: "Say", PlayerName: "QQW94", Message: "XD" },
		{ Tic: 52961, Operation: "Say", PlayerName: "QQW94", Message: "I TAKE REST" },
		{ Tic: 52985, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "OK.." },
		{ Tic: 53117, Operation: "Kick", PlayerName: "QQW94", MessageType: 3 },
		{ Tic: 53892, Operation: "Say", PlayerName: "Timothy", Message: "><" },
		{ Tic: 54266, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "WE CARRY ON?" },
		{ Tic: 54436, Operation: "Say", PlayerName: "Timothy", Message: "NOPE" },
		{ Tic: 54821, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "AREST TOO?" },
		{ Tic: 54940, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "REST" },
		{ Tic: 54980, Operation: "Say", PlayerName: "Timothy", Message: "Y" },
		{ Tic: 55055, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "KO" },
		{ Tic: 55114, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "OK" },
		{ Tic: 55285, Operation: "Say", PlayerName: "Timothy", Message: "XD" },
		{ Tic: 55470, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "EXIT?" },
		{ Tic: 56057, Operation: "Say", PlayerName: "Timothy", Message: "EXIT\"" },
		{ Tic: 56134, Operation: "Say", PlayerName: "-=d.b=- e.f.", Message: "Y" },
	],
	ActivityTimeOffset: 0.0,
	ActivityTimeScale: 0.9998,
	Videos: [
		{
			PlayerName: "-=d.b=- e.f.",
			VideoID: "JciRal0oChM",
			ZeroTime: 1.2,
		},
		{
			PlayerName: "Timothy",
			VideoID: "NPdA9ytkf78",
			ZeroTime: 1.3,
		},
		{
			PlayerName: "QQW94",
			VideoID: "82h9W4-DXEw",
			ZeroTime: 1.15,
		},
		{
			PlayerName: "sprite",
			VideoID: "J5LZSxrBjqg",
			ZeroTime: 1.2,
		},
	],
};
